import GlobalNav from "../ui/GlobalNav";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import React from "react";
import ThemeContextProvider from "./ThemeContextProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Rest Country</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <ThemeContextProvider>
          {/* <header> */}
          <GlobalNav />
          {/* </header> */}
          <main className="bg-[#fafafa] dark:bg-[#202c37]">{children}</main>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
